### ISSUE TITLE
Plot of multiple individuals' imputed genotypes

### ISSUE THREAD

**Issue by kbroman** [rqtl/qtl2plot#31]
- Add a function `plot_geno()` for visualizing the genotypes of a set of individuals (vs just one, as with `plot_onegeno()`).

**Comment by dmgatti** [comment]
I'm not sure if this is related, but we were thinking that a plot of the 36 state genotypes of all samples at a given marker.  It would be like a phenotype X genotype plot, but with all 36 unphased diplotypes.
 
![image](https://user-images.githubusercontent.com/540344/31194840-5990c818-a916-11e7-9666-76c2e53ec526.png)

**Comment by kbroman** [comment]
This issue was moved to rqtl/qtl2#19
