### ISSUE TITLE
Error thrown from plot_genes()

### ISSUE THREAD

**Issue by dmgatti** [rqtl/qtl2plot#32]
An error check at the beginning of the function for required column names might be a good idea here. That would protect you from sloppy users. Not that I know any.

stopifnot(all(c("chr", "start", "stop", "strand", "Name") %in% colnames(genes)))

Apologies. Late on a Friday afternoon. I misnamed the stop column as "end".

I get an error when calling plot_genes(). I don't see anything wrong with my data, which is pasted below.

```
> plot_genes(genes)
Error in arrange_genes(start, end + space + strwidth(name, cex = text_cex) +  :
  Must have length(start) == length(end)
In addition: Warning message:
In is.na(genes$stop) :
  is.na() applied to non-(list or vector) of type 'NULL'

> genes
    chr    start      end strand          Name
1     5  3000116  3001052      -        V1rg10
2     5  3030238  3032082      +        Gm3027
3     5  3041627  3042711      +       Gm18187
...
224   5 14974113 14978935      -       Gm10354
```

**Comment by kbroman** [comment]
Could you use `saveRDS()` to dump the object in a file and place it in a [gist](https://gist.github.com)? I don't see anything obviously wrong, and I'd like to be able to reproduce the problem on my end.

**Comment by kbroman** [comment]
Oh I see. `plot_genes()` is expecting `stop` rather than `end`.

I think I should just revise `plot_genes()` to look for `end` if there is no `stop`.

**Comment by kbroman** [comment]
Notes to self: 
- check that `start` and `stop` are non-null
- either allow, within the body of the code, that `stop` can also be `end`, or include function arguments like `start_field` and `stop_field`.

**Comment by kbroman** [comment]
And apologies that I didn't read the first paragraph in your note. 😳

**Comment by dmgatti** [comment]
All good. I was pushing past my productive period on a Friday evening. But a check for matching colnames with a meaningful error would prevent this kind of tired brain mistake.

Have a good weekend,
Dan
